# Generated by Django 3.2.9 on 2021-11-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.IntegerField()),
                ('updatedby', models.CharField(max_length=200)),
                ('updatedon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_line1', models.CharField(max_length=254)),
                ('addr_line2', models.EmailField(max_length=254)),
                ('city', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.DateTimeField()),
                ('updatedby', models.CharField(max_length=200)),
                ('updatedon', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customerdata.customerdetails')),
            ],
        ),
    ]
